name: Deploy Portfolio Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci --legacy-peer-deps
      - run: npm run build
      - run: |
          # Add dist directory to git
          git add dist
          # Configure git identity
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          # Commit built files
          git commit -m "Add built files"
          # Push to main branch with authentication
          git push https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}